
#
# Directory for config files: 'fly-cube-migration.yml', 'database.yml' and 'post-scripts.yml'
#
FLY_CUBE_MIGRATION_CONFIG_DIR: "config/"

#
# Directory for database migration files
#
FLY_CUBE_MIGRATION_DB_MIGRATIONS_DIR: "db/migrate/"
